services:
  - type: web
    name: canvas-lms-web
    runtime: docker
    dockerfilePath: ./Dockerfile.render
    plan: starter
    region: oregon
    # Remove branch specification - Render will use default branch
    envVars:
      - key: RAILS_ENV
        value: development
      - key: NODE_ENV
        value: development
      - key: CANVAS_LMS_ADMIN_EMAIL
        value: admin@example.com
      - key: CANVAS_LMS_ADMIN_PASSWORD
        value: password123
      - key: CANVAS_LMS_ACCOUNT_NAME
        value: "Canvas Dev"
      - key: CANVAS_LMS_STATS_COLLECTION
        value: opt_out
      - key: DATABASE_URL
        fromDatabase:
          name: canvas-postgres
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: canvas-redis
          property: connectionString
    buildCommand: |
      bundle install
      yarn install
      bundle exec rake db:create db:initial_setup
      bundle exec rake canvas:compile_assets

  - type: redis
    name: canvas-redis
    plan: free  # Use free plan for Redis
    region: oregon
    ipAllowList: []

databases:
  - name: canvas-postgres
    plan: free  # Use new free plan instead of legacy 'starter'
    region: oregon
    ipAllowList: []
